include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - lib/**.freezed.dart
    - lib/**.g.dart
    - integration_test/**.g.dart

linter:
  rules:
    - prefer_relative_imports
    - avoid_type_to_string
    - cancel_subscriptions
    - literal_only_boolean_expressions
    - missing_code_block_language_in_doc_comment
    - prefer_void_to_null
    - unnecessary_statements
    - always_put_required_named_parameters_first
    - always_specify_types
    - avoid_bool_literals_in_conditional_expressions
    - avoid_multiple_declarations_per_line
    - avoid_positional_boolean_parameters
    - avoid_void_async
    - combinators_ordering
    - directives_ordering
    - eol_at_end_of_file
    - matching_super_parameters
    - no_literal_bool_comparisons
    - parameter_assignments
    - prefer_asserts_with_message
    - prefer_final_in_for_each
    - prefer_final_locals
    - prefer_int_literals
    - prefer_null_aware_method_calls
    - prefer_single_quotes
    - require_trailing_commas
    - sized_box_shrink_expand
    - sort_constructors_first
    - sort_unnamed_constructors_first
    - unawaited_futures
    - unnecessary_breaks
    - unnecessary_lambdas
    - unnecessary_null_checks
    - unnecessary_parenthesis
    - unnecessary_raw_strings
    - unreachable_from_main
    - use_colored_box
    - use_decorated_box
    - use_enums
    - use_if_null_to_convert_nulls_to_bools
    - use_is_even_rather_than_modulo
    - use_named_constants
    - use_raw_strings
    - use_string_buffers
    - use_to_and_as_if_applicable
    - sort_pub_dependencies
