name: Build Android QA on Push

on:
  push:

jobs:
  android_qa_build:
    name: Android QA App Bundle Build & Upload
    runs-on: workstation.ubuntu.lts
    container:
      image: gitea.cyber-mint.com/zarply/za-flutter:3.38.4
    env:
      RELEASE_KEY_ALIAS: ${{ secrets.RELEASE_KEY_ALIAS }}
      RELEASE_KEY_PASSWORD: ${{ secrets.RELEASE_KEY_PASSWORD }}
      RELEASE_KEYSTORE: ${{ secrets.RELEASE_KEYSTORE }}
      RELEASE_STORE_PASSWORD: ${{ secrets.RELEASE_STORE_PASSWORD }}
      BASE64_KEYSTORE: ${{ secrets.BASE64_KEYSTORE }}
      SERVICE_ACCOUNT_JSON: ${{ secrets.SERVICE_ACCOUNT_JSON }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Decode Android Key Store
        run: echo $BASE64_KEYSTORE | base64 -d | tee android/app/zarply-release.keystore > /dev/null

      - name: Create key.properties
        run: |
          printf 'keyAlias=%s\nkeyPassword=%s\nstoreFile=%s\nstorePassword=%s' \
            $RELEASE_KEY_ALIAS $RELEASE_KEY_PASSWORD $RELEASE_KEYSTORE $RELEASE_STORE_PASSWORD > android/key.properties

      - name: Verify Flutter Installation
        run: flutter doctor -v

      - name: Get Project Dependencies
        run: flutter pub get --no-precompile --enforce-lockfile

      - name: Update Gradle Properties
        run: cp android/gradle.docker.properties android/gradle.properties

      - name: Optimize Gradle Wrapper For CI
        run: cp android/gradle/wrapper/gradle-wrapper.docker.properties android/gradle/wrapper/gradle-wrapper.properties

      - name: Build Android QA App Bundle
        run: |
          VERSION_LINE=$(grep '^version:' pubspec.yaml | head -n 1 | sed 's/version:[ ]*//')
          VERSION_NAME=$(echo "$VERSION_LINE" | cut -d'+' -f1)
          BUILD_NUMBER=$(echo "$VERSION_LINE" | cut -d'+' -f2)
          ENV=qa

          echo "Building QA bundle with versionName=$VERSION_NAME buildNumber=$BUILD_NUMBER"

          flutter build appbundle --release \
            --obfuscate \
            --split-debug-info=split_debug_info/ \
            --flavor $ENV \
            --build-name=$VERSION_NAME \
            --build-number=$BUILD_NUMBER \
            --dart-define-from-file=.env.$ENV

      - name: Save QA AAB Artifacts
        run: |
          mkdir -p artifacts
          mv build/app/outputs/bundle/qaRelease/app-qa-release.aab artifacts/zarply-qa.aab
          mv build/app/outputs/mapping/qaRelease/mapping.txt artifacts/appbundle_mapping.txt
          cd build/app/intermediates/merged_native_libs/qaRelease/mergeQaReleaseNativeLibs/out/lib/
          zip -r ../../../../../../../../artifacts/appbundle_symbols.zip .
          cd ../../../../../../../

      - name: Create zip file with correct timestamps
        run: zip -r artifacts-qa.zip artifacts

      - name: Store QA Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: qa-zarply
          path: artifacts-qa.zip

      - name: Upload Android QA to Play Store
        uses: r0adkll/upload-google-play@v1.1.3
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          packageName: za.co.zarply.qa
          releaseFiles: artifacts/zarply-qa.aab
          track: internal
          status: completed
          mappingFile: artifacts/appbundle_mapping.txt
          debugSymbols: artifacts/appbundle_symbols.zip

