name: On Push Mobile Builds (iOS QA & Prod)

on:
  push:
    branches: 
    tags:
      - '*-prod'
      - '*-qa'

jobs:
  # Android jobs commented out - uncomment to re-enable.
  # android_qa_build:
  #   name: Android QA App Bundle Build & Upload
  #   runs-on: workstation.ubuntu.lts
  #   container:
  #     image: gitea.cyber-mint.com/zarply/za-flutter:3.38.4
  #   env:
  #     RELEASE_KEY_ALIAS: ${{ secrets.RELEASE_KEY_ALIAS }}
  #     RELEASE_KEY_PASSWORD: ${{ secrets.RELEASE_KEY_PASSWORD }}
  #     RELEASE_KEYSTORE: ${{ secrets.RELEASE_KEYSTORE }}
  #     RELEASE_STORE_PASSWORD: ${{ secrets.RELEASE_STORE_PASSWORD }}
  #     BASE64_KEYSTORE: ${{ secrets.BASE64_KEYSTORE }}
  #     SERVICE_ACCOUNT_JSON: ${{ secrets.SERVICE_ACCOUNT_JSON }}
  #   steps:
  #     - name: Checkout Repository
  #       uses: actions/checkout@v2
  #     - name: Decode Android Key Store
  #       run: echo $BASE64_KEYSTORE | base64 -d | tee android/app/zarply-release.keystore > /dev/null
  #     - name: Create key.properties
  #       run: |
  #         printf 'keyAlias=%s\nkeyPassword=%s\nstoreFile=%s\nstorePassword=%s' \
  #           $RELEASE_KEY_ALIAS $RELEASE_KEY_PASSWORD $RELEASE_KEYSTORE $RELEASE_STORE_PASSWORD > android/key.properties
  #     - name: Verify Flutter Installation
  #       run: flutter doctor -v
  #     - name: Get Project Dependencies
  #       run: flutter pub get --no-precompile --enforce-lockfile
  #     - name: Update Gradle Properties
  #       run: cp android/gradle.docker.properties android/gradle.properties
  #     - name: Optimize Gradle Wrapper For CI
  #       run: cp android/gradle/wrapper/gradle-wrapper.docker.properties android/gradle/wrapper/gradle-wrapper.properties
  #     - name: Build Android QA App Bundle
  #       run: |
  #         VERSION_LINE=$(grep '^version:' pubspec.yaml | head -n 1 | sed 's/version:[ ]*//')
  #         VERSION_NAME=$(echo "$VERSION_LINE" | cut -d'+' -f1)
  #         BUILD_NUMBER=$(echo "$VERSION_LINE" | cut -d'+' -f2)
  #         ENV=qa
  #         echo "Building QA bundle with versionName=$VERSION_NAME buildNumber=$BUILD_NUMBER"
  #         flutter build appbundle --release \
  #           --obfuscate \
  #           --split-debug-info=split_debug_info/ \
  #           --flavor $ENV \
  #           --build-name=$VERSION_NAME \
  #           --build-number=$BUILD_NUMBER \
  #           --dart-define=FLUTTER_APP_ENV=$ENV \
  #           --dart-define-from-file=.env.$ENV
  #     - name: Save QA AAB Artifacts
  #       run: |
  #         mkdir -p artifacts
  #         mv build/app/outputs/bundle/qaRelease/app-qa-release.aab artifacts/zarply-qa.aab
  #         mv build/app/outputs/mapping/qaRelease/mapping.txt artifacts/appbundle_mapping.txt
  #         cd build/app/intermediates/merged_native_libs/qaRelease/mergeQaReleaseNativeLibs/out/lib/
  #         zip -r ../../../../../../../../artifacts/appbundle_symbols.zip .
  #         cd ../../../../../../../
  #     - name: Create zip file with correct timestamps
  #       run: zip -r artifacts-qa.zip artifacts
  #     - name: Store QA Build Artifacts
  #       uses: actions/upload-artifact@v3
  #       with:
  #         name: qa-zarply
  #         path: artifacts-qa.zip
  #     - name: Upload Android QA to Play Store
  #       uses: r0adkll/upload-google-play@v1.1.3
  #       with:
  #         serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
  #         packageName: za.co.zarply.qa
  #         releaseFiles: artifacts/zarply-qa.aab
  #         track: internal
  #         status: completed
  #         mappingFile: artifacts/appbundle_mapping.txt
  #         debugSymbols: artifacts/appbundle_symbols.zip
  #
  # android_prod_build:
  #   name: Android Prod App Bundle Build & Upload
  #   runs-on: workstation.ubuntu.lts
  #   container:
  #     image: gitea.cyber-mint.com/zarply/za-flutter:3.38.4
  #   env:
  #     RELEASE_KEY_ALIAS: ${{ secrets.RELEASE_KEY_ALIAS }}
  #     RELEASE_KEY_PASSWORD: ${{ secrets.RELEASE_KEY_PASSWORD }}
  #     RELEASE_KEYSTORE: ${{ secrets.RELEASE_KEYSTORE }}
  #     RELEASE_STORE_PASSWORD: ${{ secrets.RELEASE_STORE_PASSWORD }}
  #     BASE64_KEYSTORE: ${{ secrets.BASE64_KEYSTORE }}
  #     SERVICE_ACCOUNT_JSON: ${{ secrets.SERVICE_ACCOUNT_JSON }}
  #   steps:
  #     - name: Checkout Repository
  #       uses: actions/checkout@v2
  #     - name: Decode Android Key Store
  #       run: echo $BASE64_KEYSTORE | base64 -d | tee android/app/zarply-release.keystore > /dev/null
  #     - name: Create key.properties
  #       run: |
  #         printf 'keyAlias=%s\nkeyPassword=%s\nstoreFile=%s\nstorePassword=%s' \
  #           $RELEASE_KEY_ALIAS $RELEASE_KEY_PASSWORD $RELEASE_KEYSTORE $RELEASE_STORE_PASSWORD > android/key.properties
  #     - name: Verify Flutter Installation
  #       run: flutter doctor -v
  #     - name: Get Project Dependencies
  #       run: flutter pub get --no-precompile --enforce-lockfile
  #     - name: Update Gradle Properties
  #       run: cp android/gradle.docker.properties android/gradle.properties
  #     - name: Optimize Gradle Wrapper For CI
  #       run: cp android/gradle/wrapper/gradle-wrapper.docker.properties android/gradle/wrapper/gradle-wrapper.properties
  #     - name: Build Android Prod App Bundle
  #       run: |
  #         VERSION_LINE=$(grep '^version:' pubspec.yaml | head -n 1 | sed 's/version:[ ]*//')
  #         VERSION_NAME=$(echo "$VERSION_LINE" | cut -d'+' -f1)
  #         BUILD_NUMBER=$(echo "$VERSION_LINE" | cut -d'+' -f2)
  #         ENV=prod
  #         echo "Building Prod bundle with versionName=$VERSION_NAME buildNumber=$BUILD_NUMBER"
  #         flutter build appbundle --release \
  #           --obfuscate \
  #           --split-debug-info=split_debug_info/ \
  #           --flavor $ENV \
  #           --build-name=$VERSION_NAME \
  #           --build-number=$BUILD_NUMBER \
  #           --dart-define=FLUTTER_APP_ENV=$ENV \
  #           --dart-define-from-file=.env.$ENV
  #     - name: Save Prod AAB Artifacts
  #       run: |
  #         mkdir -p artifacts
  #         mv build/app/outputs/bundle/prodRelease/app-prod-release.aab artifacts/zarply-prod.aab
  #         mv build/app/outputs/mapping/prodRelease/mapping.txt artifacts/appbundle_mapping_prod.txt
  #         cd build/app/intermediates/merged_native_libs/prodRelease/mergeProdReleaseNativeLibs/out/lib/
  #         zip -r ../../../../../../../../artifacts/appbundle_symbols_prod.zip .
  #         cd ../../../../../../../
  #     - name: Upload Android Prod to Play Store
  #       uses: r0adkll/upload-google-play@v1.1.3
  #       with:
  #         serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
  #         packageName: za.co.zarply
  #         releaseFiles: artifacts/zarply-prod.aab
  #         track: internal
  #         status: completed
  #         mappingFile: artifacts/appbundle_mapping_prod.txt
  #         debugSymbols: artifacts/appbundle_symbols_prod.zip
  #
  ios_qa_build:
    
    name: iOS QA IPA Build & Upload
    if: endsWith(github.ref_name, '-qa')
    runs-on: workstation.mac
    env:
      FASTLANE_APPLE_API_KEY_ID: ${{ secrets.FASTLANE_APPLE_API_KEY_ID }}
      FASTLANE_APPLE_ISSUER_ID: ${{ secrets.FASTLANE_APPLE_ISSUER_ID }}
      FASTLANE_APPLE_API_KEY_PATH: ${{ secrets.FASTLANE_APPLE_API_KEY_PATH }}
      ENV: qa
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Prepare environment configuration
        run: |
          if [ -f ".env.${ENV}" ]; then
            cp ".env.${ENV}" .env
          else
            echo "No .env.${ENV} file found, skipping copy"
          fi
      - name: Verify Flutter Installation
        run: flutter doctor -v
      - name: Get Project Dependencies
        run: flutter pub get --no-precompile --enforce-lockfile
      - name: Get iOS Dependencies
        run: |
          cd ios
          pod install --repo-update
          cd ..
      - name: Generate Launcher Icons
        run: |
          dart run flutter_launcher_icons
      - name: Install Fastlane Dependencies
        run: |
          cd ios
          bundle config set --local path 'vendor/bundle'
          bundle install
          cd ..
      - name: Prepare Apple API Key
        run: |
          mkdir -p ios/fastlane

          if [ -n "$FASTLANE_APPLE_API_KEY_PATH" ]; then
            if [ -f "$FASTLANE_APPLE_API_KEY_PATH" ]; then
              echo "Using existing API key file at: $FASTLANE_APPLE_API_KEY_PATH"
              cp "$FASTLANE_APPLE_API_KEY_PATH" ios/fastlane/AuthKey.p8
            else
              if echo "$FASTLANE_APPLE_API_KEY_PATH" | base64 -d > ios/fastlane/AuthKey.p8 2>/dev/null; then
                echo "Decoded base64 API key"
              else
                echo "$FASTLANE_APPLE_API_KEY_PATH" > ios/fastlane/AuthKey.p8
                echo "Using plain text API key"
              fi
            fi
            chmod 600 ios/fastlane/AuthKey.p8

            if openssl ec -in ios/fastlane/AuthKey.p8 -noout 2>/dev/null; then
              echo "API key file is valid"
            else
              echo "Warning: API key file validation failed, but continuing..."
            fi

            echo "Apple API key prepared at ios/fastlane/AuthKey.p8"
          else
            echo "Warning: FASTLANE_APPLE_API_KEY_PATH is not set"
          fi
      - name: Build iOS QA IPA
        run: |
          VERSION_LINE=$(grep '^version:' pubspec.yaml | head -n 1 | sed 's/version:[ ]*//')
          VERSION_NAME=$(echo "$VERSION_LINE" | cut -d'+' -f1)
          BUILD_NUMBER=$(echo "$VERSION_LINE" | cut -d'+' -f2)
          flutter build ipa --release \
            --no-pub \
            --obfuscate \
            --codesign \
            --split-debug-info=split_debug_info/ \
            --dart-define=FLUTTER_APP_ENV=$ENV \
            --dart-define-from-file=.env.${ENV} \
            --flavor $ENV \
            --build-name=$VERSION_NAME \
            --build-number=$BUILD_NUMBER
      - name: Upload QA to TestFlight
        run: |
          cd ios
          export FASTLANE_APPLE_API_KEY_PATH="fastlane/AuthKey.p8"
          bundle exec fastlane ios beta

  ios_prod_build:
    name: iOS Prod IPA Build & Upload
    if: endsWith(github.ref_name, '-prod')
    runs-on: workstation.mac
    env:
      FASTLANE_APPLE_API_KEY_ID: ${{ secrets.FASTLANE_APPLE_API_KEY_ID }}
      FASTLANE_APPLE_ISSUER_ID: ${{ secrets.FASTLANE_APPLE_ISSUER_ID }}
      FASTLANE_APPLE_API_KEY_PATH: ${{ secrets.FASTLANE_APPLE_API_KEY_PATH }}
      ENV: prod
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Prepare environment configuration
        run: |
          if [ -f ".env.${ENV}" ]; then
            cp ".env.${ENV}" .env
          else
            echo "No .env.${ENV} file found, skipping copy"
          fi
      - name: Verify Flutter Installation
        run: flutter doctor -v
      - name: Get Project Dependencies
        run: flutter pub get --no-precompile --enforce-lockfile
      - name: Get iOS Dependencies
        run: |
          cd ios
          pod install --repo-update
          cd ..
      - name: Generate Launcher Icons
        run: |
          dart run flutter_launcher_icons
      - name: Install Fastlane Dependencies
        run: |
          cd ios
          bundle config set --local path 'vendor/bundle'
          bundle install
          cd ..
      - name: Prepare Apple API Key
        run: |
          mkdir -p ios/fastlane

          if [ -n "$FASTLANE_APPLE_API_KEY_PATH" ]; then
            if [ -f "$FASTLANE_APPLE_API_KEY_PATH" ]; then
              echo "Using existing API key file at: $FASTLANE_APPLE_API_KEY_PATH"
              cp "$FASTLANE_APPLE_API_KEY_PATH" ios/fastlane/AuthKey.p8
            else
              if echo "$FASTLANE_APPLE_API_KEY_PATH" | base64 -d > ios/fastlane/AuthKey.p8 2>/dev/null; then
                echo "Decoded base64 API key"
              else
                echo "$FASTLANE_APPLE_API_KEY_PATH" > ios/fastlane/AuthKey.p8
                echo "Using plain text API key"
              fi
            fi
            chmod 600 ios/fastlane/AuthKey.p8

            if openssl ec -in ios/fastlane/AuthKey.p8 -noout 2>/dev/null; then
              echo "API key file is valid"
            else
              echo "Warning: API key file validation failed, but continuing..."
            fi

            echo "Apple API key prepared at ios/fastlane/AuthKey.p8"
          else
            echo "Warning: FASTLANE_APPLE_API_KEY_PATH is not set"
          fi
      - name: Build iOS Prod IPA
        run: |
          VERSION_LINE=$(grep '^version:' pubspec.yaml | head -n 1 | sed 's/version:[ ]*//')
          VERSION_NAME=$(echo "$VERSION_LINE" | cut -d'+' -f1)
          BUILD_NUMBER=$(echo "$VERSION_LINE" | cut -d'+' -f2)
          flutter build ipa --release \
            --no-pub \
            --obfuscate \
            --codesign \
            --split-debug-info=split_debug_info/ \
            --dart-define=FLUTTER_APP_ENV=prod \
            --dart-define-from-file=.env.prod \
            --build-name=$VERSION_NAME \
            --build-number=$BUILD_NUMBER
      - name: Upload Prod to TestFlight
        run: |
          cd ios
          export FASTLANE_APPLE_API_KEY_PATH="fastlane/AuthKey.p8"
          bundle exec fastlane ios beta
