name: Publish Android to Play Store

on:
  push:
    branches:
      - '**'  

jobs:
  publish-android:
    name: Android App Bundle Build & Upload to Play Store
    runs-on: workstation.ubuntu.lts
    container:
      image: gitea.cyber-mint.com/zarply/za-flutter:3.38.4
    env:
      RELEASE_KEY_ALIAS: ${{ secrets.RELEASE_KEY_ALIAS }}
      RELEASE_KEY_PASSWORD: ${{ secrets.RELEASE_KEY_PASSWORD }}
      RELEASE_KEYSTORE: ${{ secrets.RELEASE_KEYSTORE }}
      RELEASE_STORE_PASSWORD: ${{ secrets.RELEASE_STORE_PASSWORD }}
      BASE64_KEYSTORE: ${{ secrets.BASE64_KEYSTORE }}
      SERVICE_ACCOUNT_JSON: ${{ secrets.SERVICE_ACCOUNT_JSON }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Decode Android Key Store
        run: echo "$BASE64_KEYSTORE" | base64 -d > android/app/zarply-release.keystore
      - name: Verify keystore was created
        run: |
          ls -lh android/app/zarply-release.keystore
          file android/app/zarply-release.keystore
      - name: Create key.properties
        run: |
          printf 'keyAlias=%s\nkeyPassword=%s\nstoreFile=%s\nstorePassword=%s\n' \
            "$RELEASE_KEY_ALIAS" "$RELEASE_KEY_PASSWORD" "$RELEASE_KEYSTORE" "$RELEASE_STORE_PASSWORD" > android/key.properties
      - name: Verify key.properties content
        run: |
          echo "=== key.properties content ==="
          cat android/key.properties
          echo ""
          echo "=== Verifying storeFile path ==="
          STORE_FILE=$(grep "^storeFile=" android/key.properties | cut -d'=' -f2)
          echo "storeFile value: '$STORE_FILE'"
          if [ -n "$STORE_FILE" ]; then
            echo "Checking if file exists at: android/$STORE_FILE"
            ls -lh "android/$STORE_FILE" || echo "FILE NOT FOUND!"
          else
            echo "ERROR: storeFile is empty!"
          fi
      - name: Verify Flutter Installation
        run: flutter doctor -v
      - name: Get Project Dependencies
        run: flutter pub get --no-precompile --enforce-lockfile
      - name: Update Gradle Properties
        run: cp android/gradle.docker.properties android/gradle.properties
      - name: Optimize Gradle Wrapper For CI
        run: cp android/gradle/wrapper/gradle-wrapper.docker.properties android/gradle/wrapper/gradle-wrapper.properties
      - name: Build Android App Bundle
        run: |
          TAG=$(git describe --tags --always)
          TAG_NO_V=$(echo "$TAG" | sed 's/^v//')
          
          if echo "$TAG_NO_V" | grep -q '+'; then
            VERSION=$(echo "$TAG_NO_V" | cut -d '+' -f1)
            BUILD_AND_ENV=$(echo "$TAG_NO_V" | cut -d '+' -f2)
            BUILD=$(echo "$BUILD_AND_ENV" | cut -d '-' -f1)
            ENV=$(echo "$BUILD_AND_ENV" | cut -d '-' -f2)
          else
            VERSION="1.0.0"
            BUILD=$(git rev-list --count HEAD)
            ENV=""
          fi
          
          if ! [[ "$BUILD" =~ ^[0-9]+$ ]]; then
            BUILD=$(git rev-list --count HEAD)
          fi
          
          flutter build appbundle --release \
            --obfuscate \
            --split-debug-info=split_debug_info/ \
            --build-name=$VERSION \
            --build-number=$BUILD
      - name: Save Artifacts
        run: |
          mkdir -p artifacts
          mv build/app/outputs/bundle/release/app-release.aab artifacts/zarply.aab
          mv build/app/outputs/mapping/release/mapping.txt artifacts/appbundle_mapping.txt 2>/dev/null || true
          cd build/app/intermediates/merged_native_libs/release/mergeReleaseNativeLibs/out/lib/ 2>/dev/null && \
          zip -r ../../../../../../../../artifacts/appbundle_symbols.zip . 2>/dev/null || \
          echo "Symbols not found, skipping" && cd ../../../../../../../
      - name: Create zip file with correct timestamps
        run: zip -r artifacts.zip artifacts
      - name: Store Test Results
        uses: actions/upload-artifact@v3
        with:
          name: prod-zarply
          path: artifacts.zip
      - name: Upload Android Release to Play Store
        uses: r0adkll/upload-google-play@v1.1.3
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          packageName: za.co.zarply
          releaseFiles: artifacts/zarply.aab
          track: internal
          status: completed
          mappingFile: artifacts/appbundle_mapping.txt
          debugSymbols: artifacts/appbundle_symbols.zip