name: Build and Upload

on: [ push ]

jobs:
  ios_build:
    name: iOS IPA Build & Upload
    runs-on: workstation.mac
    env:
      FASTLANE_APPLE_API_KEY_ID: ${{ secrets.FASTLANE_APPLE_API_KEY_ID }}
      FASTLANE_APPLE_ISSUER_ID: ${{ secrets.FASTLANE_APPLE_ISSUER_ID }}
      FASTLANE_APPLE_API_KEY_PATH: ${{ secrets.FASTLANE_APPLE_API_KEY_PATH }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Verify Flutter Installation
        run: flutter doctor -v
      - name: Get Project Dependencies
        run: flutter pub get --no-precompile --enforce-lockfile
      - name: Get iOS Dependencies
        run: |
          cd ios
          pod install --repo-update
          cd ..
      - name: Generate Launcher Icons
        run: |
          # Generate iOS launcher icons from the same source image used for Android
          # Source: images/icon.png (configured in flutter_launcher_icons.yaml)
          # This ensures both platforms use the same icon source
          dart run flutter_launcher_icons
      - name: Prepare Apple API Key
        run: |
          # Create directory for API key if it doesn't exist
          mkdir -p ios/fastlane
          
          # Handle API key - it might be base64 encoded or plain text
          # Try to decode as base64 first, if that fails, use as-is
          if [ -n "$FASTLANE_APPLE_API_KEY_PATH" ]; then
            # Try to decode as base64, if it fails, use the content directly
            echo "$FASTLANE_APPLE_API_KEY_PATH" | base64 -d > ios/fastlane/AuthKey.p8 2>/dev/null || \
            echo "$FASTLANE_APPLE_API_KEY_PATH" > ios/fastlane/AuthKey.p8
            chmod 600 ios/fastlane/AuthKey.p8
            echo "Apple API key prepared at ios/fastlane/AuthKey.p8"
          else
            echo "Warning: FASTLANE_APPLE_API_KEY_PATH is not set"
          fi
      - name: Build iOS IPA
        run: |
          REPO_VERSION=$(git describe --tags --always | sed 's/^v//')
          echo $REPO_VERSION
          flutter build ipa --release \
            --no-pub \
            --obfuscate \
            --codesign \
            --split-debug-info=split_debug_info/ \
            --dart-define-from-file=.env
      - name: Upload to TestFlight
        run: |
          cd ios
          # Set the API key path to the file we created
          export FASTLANE_APPLE_API_KEY_PATH="fastlane/AuthKey.p8"
          fastlane ios beta