name: mac Build and Upload

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-test:
    runs-on: workstation.mac
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: print test
        run: echo "This is a test message"