@startuml
title User Journey

start

:Login Screen;

if ("User choice") then ([Create New Wallet])
  :Backup your wallet;
  :View Wallet Private Keys;
  --> :Home Screen;
elseif ([I already have a wallet])
  :Restore Wallet (Enter Phrase);
  :Create Password;
  --> :Home Screen;
endif

stop

@enduml
